### ISSUE TITLE
Data Download Bug

### ISSUE THREAD

**Issue by DBinary** [BIMSBbioinfo/bavaria#5]
Sorry, I cannot download the dataset used in tutorials_01, there is nothing in https://drive.google.com/file/d/138_35KrnUB9Xjs4yDyzMQRqrkoqu_uwV/view?usp=sharing. could you send me the dataset? Thank u so much.

**Comment by smantz** [comment]
I realized that as well and would also be happy if you could make the datasets of the tutorials available again. Thanks a lot!

**Comment by wkopp** [comment]
Thank you for pointing this out. The previous URL has disappeared for reasons I am not sure about. I've created a new download URL here: 

https://drive.google.com/file/d/1YXciVrcUSlDf9Br-NLb4z9ZFqh2KkIuO/view?usp=share_link

I'll also update the url in the notebooks soon.

**Comment by wkopp** [comment]
You'll find this url also in the notebooks now.
